#!/usr/bin/env bash
#
# One-shot local setup: virtualenvs, dependencies, configuration files and a
# .env with freshly generated secrets. Safe to re-run — existing configuration
# is never overwritten.
#
# Usage: scripts/setup.sh [--no-venv]

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

CREATE_VENV=1
for arg in "$@"; do
  case "$arg" in
    --no-venv) CREATE_VENV=0 ;;
    -h|--help) sed -n '2,9p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) die "unknown argument: $arg (try --help)" ;;
  esac
done

need python3 "Python 3.11 or newer is required." || exit 1

PY_VERSION="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
if ! python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)'; then
  die "Python 3.11+ is required, found $PY_VERSION"
fi
ok "python $PY_VERSION"

# ── dependencies ──────────────────────────────────────────────────────

for service in common gateway indexer; do
  log "setting up $service"
  cd "$REPO_ROOT/$service" || die "cannot enter $service"
  if (( CREATE_VENV )); then
    [[ -d .venv ]] || python3 -m venv .venv
    ./.venv/bin/pip install --quiet --upgrade pip
    ./.venv/bin/pip install --quiet -e '.[dev]'
    ok "$service dependencies installed in $service/.venv"
  else
    python3 -m pip install --quiet -e '.[dev]'
    ok "$service dependencies installed into the active environment"
  fi
done
cd "$REPO_ROOT" || die "cannot enter $REPO_ROOT"

# ── configuration ─────────────────────────────────────────────────────

log "preparing configuration"
for name in tenants scan; do
  target="$REPO_ROOT/deploy/$name.yaml"
  if [[ -f "$target" ]]; then
    dim "      deploy/$name.yaml already exists, left untouched"
  else
    cp "$REPO_ROOT/deploy/$name.example.yaml" "$target"
    ok "created deploy/$name.yaml from the example"
  fi
done

# ── secrets ───────────────────────────────────────────────────────────

gen_fernet_key() {
  # Fernet needs a url-safe base64 32-byte key, not an arbitrary hex string.
  "$(py_for common)" -c \
    'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' \
    2>/dev/null || python3 -c \
    'import base64,os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    python3 -c 'import secrets; print(secrets.token_hex(24))'
  fi
}

# The pre-commit hook is what actually stops a secret reaching the remote;
# .gitignore does nothing for a file that is already tracked.
if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  "$REPO_ROOT/scripts/check-secrets.sh" --install >/dev/null && ok "pre-commit secret hook installed"
fi

ENV_FILE="$REPO_ROOT/deploy/.env"
if [[ -f "$ENV_FILE" ]]; then
  dim "      deploy/.env already exists, left untouched"
else
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh. Never commit this file.

# --- generated secrets ---
LITELLM_MASTER_KEY=$(gen_secret)
CI_TRIGGER_TOKEN=$(gen_secret)
WEBHOOK_SECRET_GITHUB=$(gen_secret)
WEBHOOK_SECRET_GITLAB=$(gen_secret)
WEBHOOK_SECRET_BITBUCKET=$(gen_secret)
KEYCLOAK_ADMIN_PASSWORD=$(gen_secret)
POSTGRES_PASSWORD=$(gen_secret)

# Encrypts provider tokens at rest. Must stay stable: losing it means
# re-entering every credential.
SECRETS_KEY=$(gen_fernet_key)

# The first administrator. Leave the password empty and one is generated and
# printed once when the stack first starts.
ADMIN_USERNAME=admin
ADMIN_PASSWORD=

# --- provider tokens for repository discovery (fill these in) ---
GITHUB_TOKEN=
GITLAB_TOKEN=
BITBUCKET_APP_PASSWORD=

# --- model backend ---
# Any model your LiteLLM proxy exposes. The default is fully local via Ollama.
LITELLM_MODEL=ollama/qwen2.5-coder:14b
OLLAMA_BASE_URL=http://ollama:11434

# --- engine ---
# Pin this in production: all engine processes sharing a cache root must be the
# same build (exact-build admission barrier).
CBM_VERSION=latest

# --- tuning ---
INDEX_CONCURRENCY=2
RESCAN_INTERVAL_S=86400
EOF
  chmod 600 "$ENV_FILE"
  ok "created deploy/.env with generated secrets"
fi

# ── verification ──────────────────────────────────────────────────────

log "verifying configuration parses"
"$(py_for gateway)" - <<'PY'
import sys
from pathlib import Path

sys.path.insert(0, "gateway")
from app.tenants import TenantRegistry

registry = TenantRegistry.load(Path("deploy/tenants.yaml"))
print(f"  tenants: {', '.join(t.name for t in registry.tenants)}")
print(f"  roles:   {', '.join(a.role.value for a in registry.role_assignments)}")
PY

"$(py_for indexer)" - <<'PY'
import sys
from pathlib import Path

sys.path.insert(0, "indexer")
from app.repos import ScanConfig

config = ScanConfig.load(Path("deploy/scan.yaml"), Path("/var/lib/repo-mcp/repos"))
print(f"  connectors: {', '.join(c.name for c in config.connectors)}")
PY
ok "configuration is valid"

cat <<EOF

${C_GREEN}Setup complete.${C_RESET}

Next:
  1. Edit ${C_BLUE}deploy/.env${C_RESET}       — add a provider token (GITHUB_TOKEN, ...)
  2. Edit ${C_BLUE}deploy/scan.yaml${C_RESET}  — point a connector at your org or group
  3. Edit ${C_BLUE}deploy/tenants.yaml${C_RESET} — map your LDAP groups to squads

Then:
  ${C_DIM}scripts/test.sh${C_RESET}          run tests and linting
  ${C_DIM}scripts/dev.sh${C_RESET}           run both services locally, no Docker
  ${C_DIM}scripts/stack.sh up${C_RESET}      bring up the full Docker stack
  ${C_DIM}scripts/debug.sh${C_RESET}         diagnose a running or broken setup

${C_DIM}Branching: develop on ${C_RESET}dev${C_DIM}. See docs/development.md.${C_RESET}
EOF
